In [1]:
import torch
import pandas as pd
from glob import glob
import numpy as np
from data import AccusleepDataset, MatiasDataset
from yaml import safe_load
from utils import AttrDict
from torch.utils.data import DataLoader
from pathlib import Path

In [3]:
config = AttrDict(safe_load(open('config/config.yaml')))

In [4]:
val_set = MatiasDataset(**config.data.matias, **config.data.conjunction)

In [5]:
val_loader = DataLoader(
    val_set,
    batch_size=64,
    shuffle=True,
    num_workers=0
)

In [6]:
x, label = next(iter(val_loader))

In [7]:
x.shape, label.shapes

(torch.Size([64, 2, 1000]), torch.Size([64]))

In [9]:
label

tensor([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
        2, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0])

In [4]:
train_set = AccusleepDataset(
    **config.data.accusleep, **config.data.conjunction
)

In [5]:
train_loader = DataLoader(
    train_set,
    batch_size=64,
    shuffle=True,
    num_workers=0
)

In [6]:
x, label = next(iter(train_loader))

In [7]:
x.shape

torch.Size([64, 2, 1000])

In [8]:
label

tensor([0, 1, 0, 2, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
        1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 0, 1, 1, 0,
        0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0])

In [9]:
train_loader.dataset.weight

tensor([0.6464, 0.7943, 5.1537])

In [29]:
from sklearn.metrics import accuracy_score

predicted = torch.randint(0, 3, label.shape)
accuracy_score(label, predicted, sample_weight=train_loader.dataset.weight[label])

0.34246745678450446

In [31]:
(label == predicted).sum().item() / label.shape[0]

0.3125

In [33]:
(((label == predicted) * train_loader.dataset.weight[label]).sum() / train_loader.dataset.weight[label].sum())

tensor(0.3425)

In [18]:
train_loader.dataset.weight

tensor([0.6464, 0.7943, 5.1537])

In [15]:
df = pd.read_csv("data/matias/20240407/data.csv")

In [15]:
df.head()

EEG1       EEG2       EEG3        EEG4        EEG5      EMG1  \
0  -7.133587  -7.277510  -6.287286  -14.053066   -9.693441  2.818389   
1 -65.990902 -71.173927 -61.571083 -104.464341  -94.103888  1.908430   
2 -41.690892 -56.898725 -55.974687 -103.493407 -112.395178 -1.402542   
3  -9.776515 -35.681407 -45.624394 -123.439903 -127.730463  3.065535   
4  -0.771619  -9.889432 -10.183221 -107.183573 -124.387806  8.352127   

        EEG6        EEG7        EEG8       EEG9       EMG2  
0   8.399216  -15.839495  -14.614401  -7.799928  -1.084852  
1   8.845400  -98.069686  -91.531687 -62.845788 -10.868201  
2  -4.406309 -108.526133 -114.613784 -77.153145  -0.915440  
3 -42.210908 -108.585485 -122.171490 -79.688085   6.175390  
4 -67.036424  -64.313452  -78.526509 -58.408978   7.832904

In [16]:
df.columns

Index(['EEG1', 'EEG2', 'EEG3', 'EEG4', 'EEG5', 'EMG1', 'EEG6', 'EEG7', 'EEG8',
       'EEG9', 'EMG2'],
      dtype='object')

In [ ]:
df_manual = pd.read_csv("data/matias/sub-MLA169_ses-20240407T003422_manual_predictions_eeg8.csv")
df_yasa = pd.read_csv("data/matias/sub-MLA169_ses-20240407T003422_manual_predictions_yasa_int_eeg8.csv")